---
version: '3.7'
services:
  prometheus:
    container_name: 'monitor_prometheus'
    hostname: 'monitor_prometheus'
    image: prom/prometheus
    volumes:
      - './prometheus:/etc/prometheus'
      - './data/prometheus:/prometheus/data'
    command: '--config.file=/etc/prometheus/config.yml --web.external-url=https://prometheus.ledyba.org/'
    expose:
      - 9090
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  alertmanager:
    container_name: 'monitor_alertmanager'
    hostname: 'monitor_alertmanager'
    image: prom/alertmanager
    volumes:
      - './alertmanager:/etc/alertmanager'
    command: '--config.file=/etc/alertmanager/config.yml --web.external-url=https://alertmanager.ledyba.org/'
    expose:
      - 9093
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  grafana:
    container_name: 'monitor_grafana'
    hostname: 'monitor_grafana'
    image: grafana/grafana
    expose:
      - 3000
    restart: always
    networks:
      - planet-link
    depends_on:
      - prometheus
    volumes:
      - './data/grafana:/var/lib/grafana'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  node-mon:
    container_name: 'monitor_node-mon'
    hostname: 'monitor_node-mon'
    image: prom/node-exporter
    expose:
      - 9100
    restart: always
    networks:
      - planet-link
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'
#
networks:
  planet-link:
    external: true
