---
version: '3.7'
services:
  prometheus:
    container_name: 'monitor_prometheus'
    hostname: 'monitor_prometheus'
    image: prom/prometheus
    volumes:
      - './prometheus:/etc/prometheus'
    command: '--config.file=/etc/prometheus/config.yml --web.external-url=https://prometheus.ledyba.org/'
    expose:
      - 9090
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  alertmanager:
    container_name: 'monitor_alertmanager'
    hostname: 'monitor_alertmanager'
    image: prom/alertmanager
    volumes:
      - './alertmanager:/etc/alertmanager'
    command: '--config.file=/etc/alertmanager/config.yml --web.external-url=https://alertmanager.ledyba.org/'
    expose:
      - 9093
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  grafana:
    container_name: 'monitor_grafana'
    hostname: 'monitor_grafana'
    image: grafana/grafana
    expose:
      - 3000
    restart: always
    networks:
      - planet-link
    depends_on:
      - prometheus
    volumes:
      - './data/grafana:/var/lib/grafana'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  node-mon:
    container_name: 'monitor_node-mon'
    hostname: 'monitor_node-mon'
    image: prom/node-exporter
    expose:
      - 9100
    restart: always
    networks:
      - planet-link
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

# CreteDB cluster
  crate-adapter:
    container_name: 'monitor_crate-adapter'
    hostname: 'monitor_crate-adapter'
    image: crate/crate_adapter
    ports:
      - 9268
    volumes:
      - './crate:/config'
    command: '--config.file=/config/adapter.yaml'
    restart: always
    networks:
      - planet-link
      - crate-link
    depends_on:
      - crate-01
      - crate-02
      - crate-03
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  crate-01:
    image: crate:latest
    ports:
      - 4200
    volumes:
      - ./data/crate/01:/data
    command:
      - 'crate'
      - '-Ccluster.name=crate-monitor-cluster'
      - '-Cnode.name=crate-01'
      - '-Cnode.data=true'
      - '-Cnetwork.host=_site_'
      - '-Cdiscovery.seed_hosts=crate-02,crate-03'
      - '-Ccluster.initial_master_nodes=crate-01,crate-02,crate-03'
      - '-Cgateway.expected_nodes=3'
      - '-Cgateway.recover_after_nodes=2'
    networks:
      - crate-link
    restart: always
    environment:
      - CRATE_HEAP_SIZE=128m
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  crate-02:
    image: crate:latest
    ports:
      - 4200
    volumes:
      - ./data/crate/02:/data
    command:
      - 'crate'
      - '-Ccluster.name=crate-monitor-cluster'
      - '-Cnode.name=crate-02'
      - '-Cnode.data=true'
      - '-Cnetwork.host=_site_'
      - '-Cdiscovery.seed_hosts=crate-01,crate-03'
      - '-Ccluster.initial_master_nodes=cratedb01,crate-02,crate-03'
      - '-Cgateway.expected_nodes=3'
      - '-Cgateway.recover_after_nodes=2'
    networks:
      - crate-link
    restart: always
    environment:
      - CRATE_HEAP_SIZE=128m
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  crate-03:
    image: crate:latest
    ports:
      - 4200
    volumes:
      - ./data/crate/03:/data
    command:
      - 'crate'
      - '-Ccluster.name=crate-monitor-cluster'
      - '-Cnode.name=crate-03'
      - '-Cnode.data=true'
      - '-Cnetwork.host=_site_'
      - '-Cdiscovery.seed_hosts=crate-01,crate-02'
      - '-Ccluster.initial_master_nodes=cratedb01,crate-02,crate-03'
      - '-Cgateway.expected_nodes=3'
      - '-Cgateway.recover_after_nodes=2'
    networks:
      - crate-link
    restart: always
    environment:
      - CRATE_HEAP_SIZE=128m
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

#
networks:
  planet-link:
    external: true
  crate-link:
    external: false

