---
version: '3.7'
services:
  prometheus:
    container_name: 'monitor_prometheus'
    hostname: 'monitor_prometheus'
    image: prom/prometheus
    volumes:
      - './conf/prometheus:/etc/prometheus'
      - './data/prometheus:/prometheus/data'
    command: '--config.file=/etc/prometheus/config.yml --web.external-url=https://prometheus.ledyba.org/'
    expose:
      - 9090
    restart: always
    depends_on: []
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  alertmanager:
    container_name: 'monitor_alertmanager'
    hostname: 'monitor_alertmanager'
    image: prom/alertmanager
    volumes:
      - './conf/alertmanager:/etc/alertmanager'
    command: '--config.file=/etc/alertmanager/config.yml --web.external-url=https://alertmanager.ledyba.org/'
    expose:
      - 9093
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  grafana:
    container_name: 'monitor_grafana'
    hostname: 'monitor_grafana'
    image: grafana/grafana
    expose:
      - 3000
    restart: always
    networks:
      - planet-link
    depends_on:
      - prometheus
    volumes:
      - './data/grafana:/var/lib/grafana'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  virtoria-metrics:
    container_name: 'monitor_victoria-metrics'
    hostname: 'monitor_victoria-metrics'
    image: 'victoriametrics/victoria-metrics:latest'
    command:
      - -retentionPeriod
      - 24
    expose:
      - '8248'
    restart: always
    networks:
      - planet-link
    volumes:
      - './conf/victoria-metrics:/etc/victoria-metrics'
      - './conf/prometheus:/etc/prometheus'
      - './data/victoria-metrics:/var/lib/victoria-metrics'
    command:
      - '--enableTCP6'
      - '--storageDataPath=/var/lib/victoria-metrics'
      - '--httpListenAddr=:8248'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

## Exporters
  node-exporter:
    container_name: 'monitor_node-exporter'
    hostname: 'monitor_node-exporter'
    image: prom/node-exporter
    expose:
      - 9100
    restart: always
    networks:
      - planet-link
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  domain-exporter:
    container_name: 'monitor_domain-exporter'
    hostname: 'monitor_domain-exporter'
    image: caarlos0/domain_exporter
    expose:
      - 9222
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  ssl-exporter:
    container_name: 'monitor_ssl-exporter'
    hostname: 'monitor_ssl-exporter'
    image: ribbybibby/ssl-exporter
    expose:
      - 9219
    restart: always
    networks:
      - planet-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'
#
networks:
  planet-link:
    external: true
