global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

rule_files: []
  #- "/var/app/prometheus/alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: 'lunar-mysql'
    static_configs:
    - targets:
      - 'lunar_mysql-mon:9104'
  - job_name: 'pleroma-postgres'
    static_configs:
    - targets:
      - 'pleroma_postgres-mon:9187'
  - job_name: 'nodoca'
    static_configs:
    - targets:
      - 'monitor_node-mon:9100'
  - job_name: 'nginx'
    static_configs:
    - targets:
      - 'porta_web-mon:9913'
