---
groups:
  - name: Down
    rules:
    - alert: WordPressIsDown
      expr: up{job='wordpress'} == 0
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "Prometheus job missing (instance {{ $labels.instance }})"
        description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
