---
groups:
  - name: Weather
    rules:
    - alert: HyperHot
      expr: weather_air_temp{location='Saitama'} >= 308 # in Kelvin.
      for: 60s
      labels:
        severity: 'critical'
      annotations:
        summary: It's too hot for humans.
        description: Stay home. Keep the air conditioner on.
    - alert: HyperHot
      expr: weather_air_temp{location='Saitama'} >= 303 # in Kelvin.
      for: 60s
      labels:
        severity: 'warning'
      annotations:
        summary: It's too hot to do exercises.
        description: Take a rest. Don't run arround the Imperial Palace.

