---
global:
  scrape_interval:     '15s'
  evaluation_interval: '15s'
  external_labels:
      monitor: 'ledyba-monitor'

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - '/etc/prometheus/rules/down.yml'
  - '/etc/prometheus/rules/weather.yml'

scrape_configs:
  - job_name: 'nodoca'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: 'lunar-mysql'
    static_configs:
      - targets:
        - 'lunar_mysqld-exporter:9104'
  - job_name: 'wordpress'
    static_configs:
      - targets: ['7io.org']
    scrape_interval: '30s'
    metrics_path: '/wp-json/metrics'
    params:
      prometheus: ['DAUfZwNRcQWVR8pC76XHLeKaSDaN4ySm']
      users: ['yes']
      posts: ['yes']
      pages: ['yes']
      autoload: ['yes']
      transient: ['yes']
      user_sessions: ['yes']
      posts_without_content: ['yes']
      posts_without_title: ['yes']
      db_size: ['yes']
    scheme: 'https'
  - job_name: 'pleroma-postgres'
    static_configs:
      - targets:
        - 'pleroma_postgres-exporter:9187'
  - job_name: 'pleroma'
    metrics_path: '/api/pleroma/app_metrics'
    static_configs:
      - targets:
        - 'pleroma_web:4000'
  - job_name: 'nginx'
    static_configs:
      - targets:
        - 'porta_nginx-exporter:9913'
  - job_name: 'weather_exporter'
    scrape_interval: '60s'
    metrics_path: '/probe'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 'weather_exporter:8080'
    params:
      app-id: ['6f2bbbdbb606f96a81a30961e8cc0d61']
    static_configs:
      - targets:
          - 'Sapporo,JP'
          - 'Aomori,JP'
          - 'Tochigi,JP'
          - 'Saitama,JP'
          - 'Tokyo,JP'
          - 'Kyoto,JP'
          - 'Osaka,JP'
          - 'Wakayama,JP'
          - 'Matsue,JP'
          - 'Fukuoka,JP'
          - 'Naha,JP'
  - job_name: 'ssl'
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'monitor_ssl-exporter:9219'
    static_configs:
      - targets:
          - '7io.org:443'
          - 'ledyba.org:443'
          - 'hexe.net:443'
          - 'open-dokidokivisual.com:443'
          - 'dokidokivisual.org:443'
  - job_name: 'domain'
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: domain
      - target_label: __address__
        replacement: 'monitor_domain-exporter:9222'
    static_configs:
      - targets:
        - '0io.org'
        - '1io.org'
        - '2io.org'
        - '3io.org'
        - '4io.org'
        - '5io.org'
        - '6io.org'
        - '7io.org'
        - '8io.org'
        - '9io.org'
        - 'ledyba.org'
        - 'hexe.org'
        - 'hexe.net'
        - 'hexe.ink'
        - 'donut-lang.org'
        - 'yoraba-taiju.org'
        - 'open-dokidokivisual.com'
        - 'dokidokivisual.org'

# Alerting specifies settings related to the Alertmanager.
alerting:
#  alert_relabel_configs:
#    [ - <relabel_config> ... ]
  alertmanagers:
    - scheme: 'http'
      static_configs:
      - targets:
        - 'alertmanager:9093'

#remote_write:
#  - url: 'http://monitor_cortex:9009/api/v1/push'
#remote_read:
#  - url: 'http://monitor_cortex:9009/api/v1/read'

# https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics#grafana-setup
remote_write:
  - url: 'http://monitor_victoria-metrics:8248/api/v1/write'
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
# remote_read is not supported in victoria-metrics
#   See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/129#issuecomment-559054357
